### ISSUE TITLE
[CRASH] anycast testing

### ISSUE THREAD

**Issue by pasanmdev** [OpenSIPS/opensips#1719]
**OpenSIPS version you are running**
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0

**Crash Core Dump**
https://pastebin.com/xaPPbx0q

**Describe the traffic that generated the bug**
I'm testing opensips anycast support in 2.4

I have two nodes setup with an anycast ip and using opensips 2.4.5.  Following scenario leads to crash opensips on node2 while other node ran out of shm mem.
Scenario

1.) Call made through node 2 and , node 2 lost bgp session for anycast IP
2.) Caller CANCEL the call and CANCEL message received by node 1 and when it pass the CANCEL message
node 2 opensips crash with below message

May 31 13:50:45 ip-10-21-76-108 /usr/sbin/opensips[26219]: CRITICAL:core:sig_usr: segfault in process pid: 26219, id: 8
May 31 13:50:45 ip-10-21-76-108 kernel: [355400.486290] opensips[26219]: segfault at 3c ip 00007f38ad1c4324 sp 00007ffc078248a0 error 4 in dialog.so[7f38ad1a1000+6b000]
May 31 13:50:45  systemd[1]: Created slice system-systemd\x2dcoredump.slice.
May 31 13:50:45  systemd[1]: Started Process Core Dump (PID 26781/UID 0).

3.) node 1 also runs out of shm memory and outputs following errors and unable to to process any calls further.

May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:core:fm_malloc: not enough free shm memory (43920 bytes left, need 322296), please increase the "-m" command line parameter!
May 31 13:50:45  /usr/sbin/opensips[21885]: INFO:core:fm_malloc: attempting defragmentation...
May 31 13:50:45  /usr/sbin/opensips[21885]: INFO:core:fm_malloc: unable to alloc a big enough fragment!
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:sip_msg_cloner: no more share memory
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:new_t: out of mem
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:t_newtran: new_t failed
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:tm_anycast_cancel: cannot handle auto-CANCEL here - send to script!

**To Reproduce**
1.) Setup 2 Nodes with an anycast IP
2.) Make a call which reaches node 2,
3.) kill bgp session to anycast ip on node 2 
4.) send a CANCEL to the ongoing call which will reach node 1
5.) node 2 crash and node 1 ran out of shm mem can see from system logs

**Relevant System Logs**
node 1 errors:
May 31 13:50:45 ip-10-21-76-108 /usr/sbin/opensips[26219]: CRITICAL:core:sig_usr: segfault in process pid: 26219, id: 8
May 31 13:50:45 ip-10-21-76-108 kernel: [355400.486290] opensips[26219]: segfault at 3c ip 00007f38ad1c4324 sp 00007ffc078248a0 error 4 in dialog.so[7f38ad1a1000+6b000]
May 31 13:50:45  systemd[1]: Created slice system-systemd\x2dcoredump.slice.
May 31 13:50:45  systemd[1]: Started Process Core Dump (PID 26781/UID 0).

node 2 errors:
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:core:fm_malloc: not enough free shm memory (43920 bytes left, need 322296), please increase the "-m" command line parameter!
May 31 13:50:45  /usr/sbin/opensips[21885]: INFO:core:fm_malloc: attempting defragmentation...
May 31 13:50:45  /usr/sbin/opensips[21885]: INFO:core:fm_malloc: unable to alloc a big enough fragment!
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:sip_msg_cloner: no more share memory
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:new_t: out of mem
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:t_newtran: new_t failed
May 31 13:50:45  /usr/sbin/opensips[21885]: ERROR:tm:tm_anycast_cancel: cannot handle auto-CANCEL here - send to script!

**OS/environment information**
 - Operating System:  Debian 9.8
 - OpenSIPS installation:  debian pkg

**Comment by razvancrainea** [comment]
@pasanmdev this should have been fixed in commit a135cec5bf4ee6447f83df217ac2e7ac8922f8bf, but unfrotunately there's no 2.4 release containing that commit yet.
Can you test with a nightly build and confirm whether the bug appears or not? Thanks!

**Comment by pasanmdev** [comment]
@razvancrainea I tried below nigthly built and crash is still there. :/
     2.4.5~20190529~1b970d85e-1 500
        500 http://apt.opensips.org stretch/2.4-nightly amd64 Packages

**Comment by razvancrainea** [comment]
Can you open the core file in gdb and run `p current_dlg_pointer`? Thanks!

**Comment by razvancrainea** [comment]
Could you please try to test again with the latest commit?
If you are using the nightly debs, you'll probably have to wait until tomorrow for them to generate, hopefully that's not a problem.

**Comment by pasanmdev** [comment]
Hi Razvan,
I tried `2.4.5~20190602~7a342463c-1` nightly build pkg and crash is still there.
when I issue p current_dlg_pointer I get below, looks like I'm missing something ? though I have opensips-dbg pkg installed.

`(gdb) p current_dlg_pointer
No symbol "current_dlg_pointer" in current context.
`

**Comment by razvancrainea** [comment]
@pasanmdev most likely the stack trace of the core dump has changed. Can you paste a new backtrace for the new core file? Thanks!

**Comment by pasanmdev** [comment]
@razvancrainea new bt attached 
https://pastebin.com/D7Bape9g

**Comment by pasanmdev** [comment]
Thanks for the quick reponse @razvancrainea as always :)
tried with latest nightly build no more crashing ! woo

**Comment by razvancrainea** [comment]
Awesome! Thanks for reporting and updating us about the progress!
