### ISSUE TITLE
[BUG] rtp_relay param values failed.

### ISSUE THREAD

**Issue by QuincyGao** [OpenSIPS/opensips#3580]
**OpenSIPS version you are running**

```
version: opensips 3.3.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 01:11:32 Feb 10 2025 with gcc 4.8.5
```

**Describe the bug**

cfg:
```
if(is_method("INVITE") && !has_totag()) {
                xlog("L_DBG","[$cfg_line][$ci]---b2b-server_new--:$rm|$rs|$tu|$socket_in(port)|$var(contact)\n");
                b2b_server_new("caller");
                create_dialog("B");
                #$rtp_relay = "body";
                rtp_relay_engage("rtpengine",0);
                b2b_client_new("callee", "sip:$tU@172.16.4.114:5080");
                # initialize B2B session
                b2b_init_request("prepaid");
                exit;
        }

```

the log:
```
 10 17:22:11 [1009] DBG:b2b_entities:b2b_search_htable_next_dlg: searching  callid 32[84d49a1a61584216a00e5136508cedca]
Feb 10 17:22:11 [1009] DBG:b2b_entities:b2b_search_htable_next_dlg: searching   totag 22[B2B.369.458.1739179329]
Feb 10 17:22:11 [1009] DBG:b2b_entities:b2b_search_htable_next_dlg: searching fromtag 32[07f0d3e353cc44429693beb80e3784ba]
Feb 10 17:22:11 [1009] DBG:b2b_entities:b2b_search_htable_next_dlg: Match for server dlg [0x7f3621cc82f8] dlg->uas_tran=[0x7f3621cc85e0]
Feb 10 17:22:11 [1009] DBG:b2b_entities:b2b_send_reply: Send reply 200 INVITE, for dlg [0x7f3621cc82f8]->[B2B.369.458.1739179329]
Feb 10 17:22:11 [1009] DBG:core:parse_headers: flags=ffffffffffffffff
Feb 10 17:22:11 [1009] DBG:tm:run_any_trans_callbacks: trans=0x7f3621cc85e0, callback type 262144, id 4 entered
Feb 10 17:22:11 [1009] DBG:core:parse_headers: flags=10
Feb 10 17:22:11 [1009] DBG:rtp_relay:rtp_relay_offer: callid=[64.0] ftag=[to_tag] ttag=[from_tag] type=[] in-iface=[] out-iface=[] ctx-flags=[] flags=[] peer-flags=[]
Feb 10 17:22:11 [1009] DBG:rtpengine:rtpe_function_call: proxy reply: d3:sdp278:v=0
o=FreeSWITCH 1739149312 1739149313 IN IP4 172.16.4.114
s=FreeSWITCH
t=0 0
m=audio 32942 RTP/AVP 96 101
c=IN IP4 172.16.4.111
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:101 telephone-event/48000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:32943
a=ptime:20
6:result2:oke
Feb 10 17:22:11 [1009] ERROR:core:pv_set_value: bad parameters
Feb 10 17:22:11 [1009] ERROR:rtpengine:rtpe_function_call: setting rtpengine pvar failed
Feb 10 17:22:11 [1009] ERROR:core:pv_get_spec_value: bad parameters
Feb 10 17:22:11 [1009] ERROR:rtpengine:rtpengine_api_offer: could not retrieve the value of the used rtpengine!
Feb 10 17:22:11 [1009] DBG:core:parse_headers: flags=ffffffffffffffff

```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Can this be reproduced for every call, or does it happen once in a while?

**Comment by QuincyGao** [comment]
Yes, every Call can reproduce.

**Comment by razvancrainea** [comment]
How do you define you rtpengine nodes? through script, or db?

**Comment by razvancrainea** [comment]
I've just pushed a fix for this - can you please give it another try and let me know if you're still having trouble?

**Comment by QuincyGao** [comment]
ok, thanks, I will try it later.

**Comment by QuincyGao** [comment]
I checked the code twice and unfortunately the problem is still there.
```
+++ b/opensips-3.3.10/modules/rtp_relay/rtp_relay_ctx.c
@@ -397,6 +397,7 @@ static void rtp_relay_b2b_local_reply(struct cell* t, int type,
        }
        memset(&info, 0, sizeof info);
        info.body = body;
+       info.msg = ps->rpl;
        LM_RTP_DBG("sess=%p late=%d ongoing=%d index=%d\n",
                        sess, rtp_sess_late(sess), rtp_sess_ongoing(sess), leg->index);
 
```
the sceen is that: 
1007 register on opensips(172.16.4.111:5360), 1008 register on fs(172.16.4.114:5080).
the 1007 call  1008 , then 1008 answer, then the error occurs. 

here is my opensips.cfg
[opensips_3.3.bak.zip](https://github.com/user-attachments/files/18904835/opensips_3.3.bak.zip)

**Comment by QuincyGao** [comment]
up

**Comment by QuincyGao** [comment]
up

**Comment by QuincyGao** [comment]
up
