### ISSUE TITLE
JSON Parsing Integers

### ISSUE THREAD

**Issue by danbogos** [OpenSIPS/opensips#494]
Hey Guys,

My scenario: using jsonrpc over http to get information from a remote server inside OpenSIPS.

Request and reply will look like this:
```
T 2015/05/03 10:23:46.296052 127.0.0.1:60767 -> 127.0.0.1:2080 [AP]
POST /jsonrpc HTTP/1.1.
Host: 127.0.0.1:2080.
Accept: */*.
Content-Type: application/json.
Content-Length: 112.
.
{ "id": "1", "method": "ApierV1.GetMaxSessionTime", "params": [ { "Account": "1001", "Destination": "1002" } ] }
May  3 10:23:46 OsipsDev1 /usr/sbin/opensips[2910]: { "id": "1", "method": "ApierV1.GetMaxSessionTime", "params": [ { "Account": "1001", "Destination": "1002" } ] }
#
T 2015/05/03 10:23:46.296983 127.0.0.1:2080 -> 127.0.0.1:60767 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Sun, 03 May 2015 08:23:46 GMT.
Content-Length: 36.
.
{"id":"1","result":-1,"error":null}
```

When receiving the answer, I will use the following xlog statement in opensips:
```
xlog("In CGR_AUTH_REPLY, reply received: $json(cgr_auth_reply), result: $json(cgr_auth_reply/result)");
```

The log would be:
```
#May  3 10:23:46 OsipsDev1 /usr/sbin/opensips[2910]: In CGR_AUTH_REPLY, reply received: {"id":"1","result":-1,"error":null}#012, result: <null>
```

As you can see the reply is properly logged as a serialized json but when extracting the attribute which is an integer, it shows as null.

Ta,
DanB

**Comment by vladpaiu** [comment]
Hello,

I have just committed a fix for this ( 3bf8b49ec8ee3d29409c75e54581141792ee54e9 )
Please pull the latest sources and let me know if all is ok now.

Best Regards,
Vlad

**Comment by danbogos** [comment]
Hi Vlad,

Thank you for your feedback!

I have just tested this with latest master and still the same issue:
```
#May  5 10:44:37 OsipsDev1 /usr/sbin/opensips[23486]: In CGR_AUTH_REPLY, reply received: {"id":"1","result":-1,"error":null}#012, result: <null>

root@OsipsDev1:/etc# opensips -V
version: opensips 2.1-rc2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 59d7d48
main.c compiled on 18:49:24 May  2 2015 with gcc 4.7

```

Thanks,
DanB

**Comment by vladpaiu** [comment]
Hello Dan,

The issue is not replicating on my end. Sorry to ask weird questions, but are you sure you have recompiled the JSON module ? 

Best Regards,
Vlad

**Comment by danbogos** [comment]
Hey Vlad,

You are right about that, it appears that the master produce 2.1-rc1 packages (branch 2.1 give rc2 ones), so I was confused and installed same rc2 since they looked newer to me :).

Sorry will retest and confirm you results.

DanB

**Comment by danbogos** [comment]
Hey Vlad,

There should be some catch since in my case the issue still occurs. 
The module looks like fresh compiled (out of master):
```
root@OsipsDev1:/usr/local/src/opensips/opensips_master# ls -la /usr/lib/opensips/modules/ | grep json
-rw-r--r-- 1 root root  23912 May  5 11:35 json.so
```

```
root@OsipsDev1:/usr/local/src/opensips/opensips_master# #
T 2015/05/05 12:55:20.185506 127.0.0.1:42969 -> 127.0.0.1:2080 [AP]
POST /jsonrpc HTTP/1.1.
Host: 127.0.0.1:2080.
Accept: */*.
Content-Type: application/json.
Content-Length: 112.
.
{ "id": "1", "method": "ApierV1.GetMaxSessionTime", "params": [ { "Account": "1001", "Destination": "1001" } ] }
May  5 12:55:20 OsipsDev1 /usr/sbin/opensips[12314]: { "id": "1", "method": "ApierV1.GetMaxSessionTime", "params": [ { "Account": "1001", "Destination": "1001" } ] }
May  5 12:55:20 OsipsDev1 /usr/sbin/opensips[12314]: { "id": "1", "method": "ApierV1.GetMaxSessionTime", "params": [ { "Account": "1001", "Destination": "1001" } ] }
#
T 2015/05/05 12:55:20.186078 127.0.0.1:2080 -> 127.0.0.1:42969 [AP]
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Tue, 05 May 2015 10:55:20 GMT.
Content-Length: 36.
.
{"id":"1","result":-1,"error":null}

#May  5 12:55:20 OsipsDev1 /usr/sbin/opensips[12314]: In CGR_AUTH_REPLY, reply received: {"id":"1","result":-1,"error":null}#012, result: <null>
```

My way to log that line:
```
xlog("In CGR_AUTH_REPLY, reply received: $json(cgr_auth_reply), result: $json(cgr_auth_reply/result)");
```

If you get time, can u maybe ping me on IRC so we can troubleshoot more interactively?

Thanks,
DanB

**Comment by vladpaiu** [comment]
Closing this - after further talk on IRC, the underlying issue was related to the fact that JSON variables were used to propagate info between ASYNC route jumps, which is not supposed to work since JSON variables are stored in PKG mem.
