### ISSUE TITLE
transformation documention typos

### ISSUE THREAD

**Issue by di-shi** [OpenSIPS/opensips#913]
In http://www.opensips.org/Documentation/Script-Tran-2-2, base64 string transformation names are base64encode and base64decode. But in OpenSIPS-2.2.0, the names are b64encode and b64decode.

**Comment by liviuchircu** [comment]
Fixed! Thank you for reporting, @di-shi !

**Comment by di-shi** [comment]
Not fully fixed yet in examples. :)

1.26 {s.b64encode}
Represents binary input data in an ASCII string format. 
$var(in) = "\x2\x3\x4\x5!@#%^&*";
$(var(in){s.**_base64encode_**})   => "AgMEBSFAIyVeJio="
1.27 {s.b64decode}
Assumes input is a Base64 string and decodes as many characters as possible. 
$var(in) = "AgMEBSFAIyVeJio=";
$(var(in){s.**_base64encode_**})   => "\x2\x3\x4\x5!@#%^&*"

**Comment by liviuchircu** [comment]
Done! :)
